customer_app/urls.py
from django.urls import path
from .import views

app_name='customer_app'

urlpatterns =[
    path('home',views.home,name='home'),
    path('customer_master',views.customer_master,name='customer_master'),
    path('cart',views.cart,name='cart'),
    path('change_password',views.change_password,name='change_password'),
    path('logout',views.logout,name='logout'),
    path('demo',views.demo,name='demo')
    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecommerce_app.urls')),
    path('seller_app/',include('seller_app.urls')),
    path('customer_app/',include('customer_app.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

customer_app/models.py
from django.db import models

# Create your models here.

customer_app/views.py
from django.shortcuts import render,redirect
from seller_app.models import Product
from ecommerce_app.models import Customer

def home(request):

    products = Product.objects.all()
    return render(request,"customer_app/home.html",{'products': products})

def customer_master(request):
    customer = Customer.objects.get(id= request.session['customer'])
    return render(request,'customer_app/customer_master.html',{'customer':customer})

def cart(request):
    return render(request,'customer_app/cart.html')

def logout(request):
    del request.session['customer']
    request.session.flush()
    return redirect( 'ecommerce_app:home' )

def change_password(request):


    msg = ''
    if request.method == 'POST':
        current_password = request.POST['current_password']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            
            if len(password) >= 8:


                customer = Customer.objects.get(id= request.session['customer'])

                if customer.customerpassword == current_password:

                    Customer.objects.filter(id= request.session['customer']).update(customerpassword = confirm_password)
                    
                    msg = 'Password changed succesfully'
                else:
                    msg = 'Invalid password'
            else:
                msg = 'password should be min 8 characters'
        else:
            msg = 'password does not match'

     

    return render(request,'customer_app/change_password.html',{'message':msg})



def demo(request):
    products = Product.objects.all()
    return render(request,'customer_app/demo.html',{'products': products})

customer_app/templates/customer_app/cart.html
{% extends "customer_app/customer_master.html" %}
{% load static %}
{% block header %}
<style>
    table{
        border:solid 1px black;
        border-radius: 4px;
    }
</style>
 

{% endblock %}



{% block content %}
 

{% endblock %}

customer_app/templates/customer_app/change_password.html
{% extends "customer_app/customer_master.html" %}
{% load static %}
{% block header %}
<style>
    form {
        display: flex;
        flex-direction: column;
        align-items: center;

        margin-top: 50px;
    }

    .form {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 500px;
    }

    input[type=text],
    [type=password] {
        margin: 10px;
        padding: 10px;
        width: 300px;
        border-radius: 5px;
        border: 1px solid black;
    }

    select {
        margin: 10px;
        padding: 10px;
        width: 150px;
        border-radius: 5px;
        border: 1px solid black;
    }

    input[type=submit] {
        background-color: #4CAF50;
        color: white;
        border: none;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 10px;
        border-radius: 5px;
        cursor: pointer;
    }
</style>
{% endblock %}





{% block content %}

<div class="container-fluid form">
    <table>
        <form method="POST">
            {% csrf_token %}
            <tr>
                <td><label for="">Current Password :</label></td>
                <td><input type="text" name="current_password"></td>
            </tr>
            <tr>
                <td><label for="">New Password :</label></td>
                <td><input type="password" name="password"></td>
            </tr>
            <tr>
                <td><label for="">Confirm Password :</label></td>
                <td><input type="password" name="confirm_password"></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit"></td>
            </tr>
        </form>
        <tr>
            <td>

            </td>
        </tr>
    </table>
    {{ message }}
</div>

{% endblock %}

customer_app/templates/customer_app/customer_master.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>

  <link rel="stylesheet" href="{% static 'css/master.css' %}">

  <link rel="stylesheet"
    href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
  <link rel="stylesheet"
    href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">

  <style>
    .navv {
      display: flex;
      justify-content: space-evenly;
    }

    i {
      text-transform: capitalize;
      font-family: 'Times New Roman', Times, serif;
    }
  </style>
  {% block header %}

  {% endblock %}
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">

        <a class="navbar-brand" href="#"><i class="lab la-amazon">Amazon</i></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navv" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#"></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"> </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                <h6> </h6>
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="">Edit Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'customer_app:change_password' %}">Change Password</a></li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url 'customer_app:logout' %}">Logout</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'customer_app:cart' %}">
                <i class="las la-shopping-cart">Cart</i> </a>
            </li></a>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'customer_app:demo' %}">
                <i class=" ">demo</i> </a>
            </li></a>

          </ul>



        </div>
      </div>
    </nav>
  </header>

  <div class="container-fluid">
    {% block content %}

    {% endblock %}
  </div>

</body>

</html>

customer_app/templates/customer_app/demo.html
{% extends "customer_app/customer_master.html" %}
{% load static %}
{% block header %}
<style>
     
</style>
 

{% endblock %}



{% block content %}
<div class="container-fluid">
    <div class="row">
      {% for product in products %}
      <div class="col-md-3">
  
  
        <div class="card" style="width: 15rem;">
            <img src="{{product.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">{{ product.product_name }}</h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
          </div>
        </div>
      {% endfor %}
    
  </div>
  </div>
 

{% endblock %}

customer_app/templates/customer_app/home.html
{% extends "customer_app/customer_master.html" %}
{% load static %}
{% block header %}
<style>
  .product-card {
    width: 300px;
    border: 1px solid #ccc;
    border-radius: 4px;
    padding: 10px;
  }

  .product-card img {
    width: 100%;
    height: auto;
  }

  .product-card .product-title {
    font-size: 18px;
    font-weight: bold;
    margin: 10px 0;
  }

  .product-card .product-price .product-description {
    font-size: 16px;
    color: #888;
    margin-bottom: 10px;
  }

  .product-card .btn {
    display: inline-block;
    padding: 8px 12px;
    background-color: #4CAF50;
    color: white;
    text-decoration: none;
    border-radius: 4px;
    font-size: 14px;
  }

  img {
    width: auto;
    aspect-ratio: 3/2;
    object-fit: contain;


  }
</style>


{% endblock %}



{% block content %}


<div class="container-fluid" style="padding: 20px;">
  <div class="row">
    {% for product in products %}
    <div class="col-md-3">


      <div class="card" style="width: 15rem;">
        <img src="{{product.image.url }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{ product.product_name }}</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
            content.</p>
          <button type="submit" class="btn btn-primary">Add to Cart</button>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>
</div>


{% endblock %}