ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecommerce_app.urls')),
    path('seller_app/',include('seller_app.urls')),
    path('customer_app/',include('customer_app.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

seller_app/urls.py
from django.urls import path
from .import views

app_name='seller_app'

urlpatterns =[
    path('seller_master',views.seller_master,name='seller_master'),
    path('add_product',views.add_product,name='add_product'),
    path('home',views.home,name='home'),
    path('logout',views.logout,name='logout'),

    path('catalogue',views.catalogue,name='catalogue'),
    path('update_stock',views.update_stock,name='update_stock'),
    path('update_password',views.update_password,name='update_password'),
    path('edit',views.edit,name='edit'),





]

seller_app/models.py
from django.db import models
from ecommerce_app.models import Seller1
# Create your models here.

class Product(models.Model):
    product_name = models.CharField(max_length=30)  
    seller = models.ForeignKey(Seller1, on_delete = models.CASCADE) 
    description=models.CharField(max_length = 100)
    stock=models.IntegerField()
    code=models.CharField(max_length=20)
    price=models.FloatField()
    image = models.ImageField(upload_to  = 'product/')

    class Meta:
        db_table = 'product_tb'

seller_app/views.py
from django.shortcuts import render,redirect
from ecommerce_app.models import Seller1
from .models import Product
# Create your views here.

def seller_master(request):
    seller = Seller1.objects.get(id= request.session['seller'])
    return render(request,'seller_app/seller_master.html',{'seller':seller})
    

def add_product(request):
    msg=''
    if request.method =='POST':
        product_name = request.POST['p_name'].lower()
        description = request.POST['p_des']
        stock = request.POST['p_stock']
        code = request.POST['p_code']
        price = request.POST['p_price']
        image = request.FILES['p_image']
        product_exist = Product.objects.filter(seller = request.session['seller'],code = code).exists()


        if not product_exist:
            product = Product(
                product_name = product_name,
                description = description,
                stock = stock,
                code = code,
                price = price,
                image = image,
                seller_id = request.session['seller']

                
            )
            product.save()
            msg='Product Added Succesfully'

        else:
            msg = 'Product Exist'
 
    return render(request,'seller_app/add_product.html',{'message': msg})


def home(request):
    sellers = Seller1.objects.get(id= request.session['seller'])
    return render(request,'seller_app/home.html',{'seller':sellers})
    

def catalogue(request):
    products = Product.objects.filter(seller = request.session['seller'])
    return render(request,'seller_app/catalogue.html',{'products': products})
    
    
def update_stock(request):
    return render(request,'seller_app/update_stock.html')


def logout(request):
    del request.session['seller']
    request.session.flush()
    return redirect('ecommerce_app:seller_login')


def update_password(request):
    msg = ''
    if request.method == 'POST':
        current_password = request.POST['current_password']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            
            if len(password) >= 8:


                seller = Seller1.objects.get(id= request.session['seller'])

                if seller.password == current_password:

                    seller.password = confirm_password
                    seller.save()
                    
                    msg = 'Password changed succesfully'
                else:
                    msg = 'Invalid password'
            else:
                msg = 'password should be min 8 characters'
        else:
            msg = 'password does not match'

    return render(request,'seller_app/update_password.html',{'message': msg})
def edit(request):
    return render(request,'seller_app/edit_profile.html')

seller_app/templates/seller_app/add_product.html
{% extends "seller_app/seller_master.html" %}
{% load static %}
{% block header %}
<style>
	form {
		display: flex;
		flex-direction: column;
		align-items: center;

		margin-top: 50px;
	}

	.form {
		display: flex;
		flex-direction: column;
		align-items: center;
	}

	input[type=text] {
		margin: 10px;
		padding: 10px;
		width: 500px;
		border-radius: 5px;
		border: 1px solid #ccc;
	}

	input[type=submit] {
		background-color: #4CAF50;
		color: white;
		border: none;
		padding: 10px 20px;
		text-align: center;
		text-decoration: none;
		display: inline-block;
		font-size: 16px;
		margin: 10px;
		border-radius: 5px;
		cursor: pointer;
	}

	label {
		margin: 10px;
	}

	.signup {
		text-align: center;
	}
</style>



{% endblock %}



{% block content %}
<div class="container-fluid form">
	<div class="" style="text-align: center; margin-top: 20px; margin-bottom: 20px;">
		<h3>ADD PRODUCT</h3>
	</div>
	<table>
		{{ message }}



		<form action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}

			<tr>
				<td><label for="name">Product Name:</label></td>
				<td><input type="text" id=" " name="p_name"></td>
			</tr>

			<tr>
				<td><label for="mobilno">Description :</label></td>
				<td><input type="text" name="p_des"></td>
			</tr>

			<tr>
				<td><label for="email">Product Stock:</label></td>
				<td><input type="text" name="p_stock"></td>

			</tr>




			<tr>
				<td><label for="">Product Code :</label></td>
				<td><input type="text" name="p_code"></td>
			</tr>

			<tr>
				<td><label for="">Product Price :</label></td>
				<td><input type="text" name="p_price"></td>
			</tr>
			<tr>
				<td><label for="">Image</label></td>
				<td><input type="file" name="p_image"></td>
			</tr>
			<tr>
				<td></td>
				<td><input type="submit" value="Submit"></td>
			</tr>

		</form>
	</table>
</div>


{% endblock %}

seller_app/templates/seller_app/catalogue.html
{% extends "seller_app/seller_master.html" %}
{% load static %}
{% block header %}
<style>
  img {
    width: auto;
    aspect-ratio: 3/2;
    object-fit: contain;


  }
</style>
{% endblock %}




{% block content %}


<div class="container-fluid" style="padding: 20px;">
  <div class="row">
    {% for product in products %}
    <div class="col-md-3">


      <div class="card" style="width: 15rem;">
        <img src="{{product.image.url }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{ product.product_name }}</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
            content.</p>
          <button type="submit" class="btn btn-primary">Add to Cart</button>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>
</div>






{% endblock %}

seller_app/templates/seller_app/edit_profile.html
{% extends "seller_app/seller_master.html" %}
{% load static %}
{% block header %}
<style>

</style>
{% endblock %}




{% block content %}
<div class="container-fluid form">
    <table>
        <form method="POST">
            {% csrf_token %}
            <tr>
                <td><label for="">Seller Id :</label></td>
                <td><input type="text" name="sellerid"></td>
            </tr>
            <tr>
                <td><label for="">Name :</label></td>
                <td><input type="text" name="name"></td>
            </tr>
            <tr>
                <td><label for="">Company Name :</label></td>
                <td><input type="text" name="companyname"></td>
            </tr>
            <tr>
                <td><label for="">mobile No :</label></td>
                <td><input type="text" name="mobileno"></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit"> </td>
            </tr>
        </form>
        <tr>
            <td>

            </td>
        </tr>
    </table>
    {{ message }}
</div>


{% endblock %}

seller_app/templates/seller_app/home.html
{% extends "seller_app/seller_master.html" %}
{% load static %}
{% block header %}
<style>
  .seller {
    height: 500px;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  td {
    text-align: left;
  }

  h2 {
    text-transform: capitalize;
    font-family: 'Times New Roman', Times, serif;
  }
</style>
{% endblock %}




{% block content %}
<!-- <div class="container-fluid"><img src="{% static 'images/seller.jpg' %}" alt=""></div> -->
<div class="container-fluid seller">
  <div class="card mb-3" style="max-width: 640px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="{{ seller.image.url }}" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h2 class="card-title">Hello, {{ seller.sellername }}</h2>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Pariatur ipsam eveniet adipisci, quae accusantium
            iusto?</p>

          <table>
            <tr>
              <td><label for="">Company Name </label></td>
              <td> :{{ seller.companyname }}</td>
            </tr>
            <tr>
              <td><label for="">Phone No </label></td>
              <td> :{{ seller.mobileno }}</td>
            </tr>

          </table>

        </div>
      </div>
    </div>
  </div>
</div>













{% endblock %}

seller_app/templates/seller_app/seller_master.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="{% static 'css/seller_master.css' %}">

    <link rel="stylesheet"
        href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
    <link rel="stylesheet"
        href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">

    <style>
        * {
            padding: 0;
        }

        body {
            margin: 0;
            padding: 0;
            font-family: 'Times New Roman', Times, serif;


        }

        nav a {
            text-decoration: none;
            color: black;
        }

        .seller-dash {
            display: flex;
            flex-wrap: wrap;
            flex-direction: column;
            height: 500px;
            padding: 20px;
            justify-content: space-evenly;
            background-color: white;
            text-align: left;


        }

        .seller-dash a {
            text-decoration: none;
            color: black;
        }

        .seller-dash li {
            background-color: rgba(var(--bs-tertiary-bg-rgb), var(--bs-bg-opacity)) !important;

            list-style: none;
            padding: 0;

        }


        .seller-nav {
            height: 60px;
        }

        a:hover {
            color: blue;
        }

        h5 {
            font-family: 'Times New Roman', Times, serif;
            text-transform: capitalize;
        }
    </style>
    {% block header %}

    {% endblock %}
</head>

<body>

    <div class="container-fluid text-center">
        <div class="row container-fluid">
            <div class="col-2 "> </div>

            <div class="col-10 seller-nav">
                <nav class="navbar bg-body-tertiary nav">
                    <div class="container-fluid">
                        <a class="navbar-brand" href="">
                            <i class="lab la-amazon"> Amazon</i>

                        </a>
                        <i class="las la-home"><a href="{% url 'seller_app:home'%}"> Home </a></i>
                    </div>

                </nav>
            </div>

        </div>
        <div class="container-fluid text-center">
            <div class="row container-fluid">
                <div class="col-2 seller-dash">
                    <img src="{{ seller.image.url }}" alt="" style="width: 50px; border-radius: 50%;">
                    <i class="las la-user">
                        <h5>{{ seller.sellername }}</h5>
                    </i>
                    <i class="las la-igloo"><a href="{% url 'seller_app:home'%}"> Home</a></i>
                    <i class="las la-user"><a href="{% url 'seller_app:edit'%}">Edit Profile</a></i>
                    <i class="las la-edit"><a href="{% url 'seller_app:update_password' %}"> Update Password</a></i>
                    <i class="las la-tshirt"><a href="{% url 'seller_app:catalogue'%}"> Product Catalogue</a></i>
                    <i class="las la-plus-square"><a href="{% url 'seller_app:add_product'%}"> Add Product</a></i>
                    <i class="las la-clock"><a href=""> Recent Orders</a></i>
                    <i class="las la-history"><a href=""> Order History</a></i>
                    <i class="las la-database"><a href="{% url 'seller_app:update_stock'%}"> Update Stock</a></i>
                    <li></li>
                    <i class="las la-sign-out-alt"><a href="{% url 'seller_app:logout'%}">Logout</a></i>

                </div>
                <div class="col-10 content">







                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
    </div>


</body>

</html>

seller_app/templates/seller_app/update_password.html
{% extends "seller_app/seller_master.html" %}
{% load static %}
{% block header %}
<style>
    form {
        display: flex;
        flex-direction: column;
        align-items: center;

        margin-top: 50px;
    }

    .form {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 500px;
    }

    input[type=text],
    [type=password] {
        margin: 10px;
        padding: 10px;
        width: 300px;
        border-radius: 5px;
        border: 1px solid black;
    }

    select {
        margin: 10px;
        padding: 10px;
        width: 150px;
        border-radius: 5px;
        border: 1px solid black;
    }

    input[type=submit] {
        background-color: #4CAF50;
        color: white;
        border: none;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 10px;
        border-radius: 5px;
        cursor: pointer;
    }
</style>
{% endblock %}





{% block content %}

<div class="container-fluid form">
    <table>
        <form method="POST">
            {% csrf_token %}
            <tr>
                <td><label for="">Current Password :</label></td>
                <td><input type="text" name="current_password"></td>
            </tr>
            <tr>
                <td><label for="">New Password :</label></td>
                <td><input type="password" name="password"></td>
            </tr>
            <tr>
                <td><label for="">Confirm Password :</label></td>
                <td><input type="password" name="confirm_password"></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit"> </td>
            </tr>
        </form>
        <tr>
            <td>

            </td>
        </tr>
    </table>
    {{ message }}
</div>

{% endblock %}

seller_app/templates/seller_app/update_stock.html
{% extends "seller_app/seller_master.html" %}
{% load static %}
{% block header %}
<style>
	form {
		display: flex;
		flex-direction: column;
		align-items: center;

		margin-top: 50px;
	}

	.form {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		height: 200px;
	}

	input[type=text] {
		margin: 10px;
		padding: 10px;
		width: 300px;
		border-radius: 5px;
		border: 1px solid black;
	}

	select {
		margin: 10px;
		padding: 10px;
		width: 150px;
		border-radius: 5px;
		border: 1px solid black;
	}

	input[type=submit] {
		background-color: #4CAF50;
		color: white;
		border: none;
		padding: 10px 20px;
		text-align: center;
		text-decoration: none;
		display: inline-block;
		font-size: 16px;
		margin: 10px;
		border-radius: 5px;
		cursor: pointer;
	}
</style>
{% endblock %}




{% block content %}
<div class="container-fluid form">
	<table>
		<form action="POST">
			{% csrf_token %}
			<tr>
				<td>Products</td>
				<td>Current Stock</td>
				<td>New Stock</td>
			</tr>
			<tr>
				<td><select name="products" id="">
						<option value="">Headphone</option>
						<option value="">Speaker</option>
						<option value="">Gamepad</option>
						<option value="">Ps4</option>
					</select></td>
				<td><input type="text"></td>
				<td><input type="text"></td>
			</tr>
			<tr>
				<td></td>
				<td><input type="submit"></td>
			</tr>
		</form>
	</table>
</div>


{% endblock %}