ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecommerce_app.urls')),
    path('seller_app/',include('seller_app.urls')),
    path('customer_app/',include('customer_app.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce_app/urls.py
from django.urls import path
from .import views

app_name='ecommerce_app'

urlpatterns =[
    path('home',views.home,name='home'),
    path('admin_login',views.admin_login,name='admin_login'),
    path('customer_signup',views.customer_signup,name='customer_signup'),
    path('master',views.master,name='master'),
    path('customer_login',views.customer_login,name='customer_login'),
    path('seller_login',views.seller_login,name='seller_login'),
    path('seller_signup',views.seller_signup,name='seller_signup'),

]

ecommerce_app/models.py
from django.db import models

# Create your models here.
class Seller1(models.Model):
    sellername=models.CharField(max_length=100)
    mobileno=models.BigIntegerField()
    email=models.CharField(max_length=100)
    companyname=models.CharField( max_length=100)
    password=models.CharField(max_length=100,default='')
    username=models.IntegerField(default=1)
    ac_holder_name = models.CharField(max_length = 30 ,default = '')
    ifsc = models.CharField(max_length = 20, default = '')
    branch= models.CharField(max_length = 30, default = '')
    ac_no = models.CharField(max_length = 30, default = '')
    image = models.ImageField(upload_to  = 'seller/')
    gender = models.CharField(max_length = 30,default='')

    class Meta:
            db_table = 'seller_tb'


class Customer(models.Model):
    customername=models.CharField(max_length=100)
    customermobile=models.BigIntegerField()
    customermail=models.CharField(max_length=100)
    customerpassword=models.CharField(max_length=100,default='')

    class Meta:
        db_table = 'customer_tb'

ecommerce_app/views.py
import random
from django.shortcuts import render,redirect
from django.core.mail import send_mail

from ecommerce_app.models import Seller1
from ecommerce_app.models import Customer
from django.conf import settings

# Create your views here.

def master(request):
    return render(request,'ecommerce_app/master.html')

def home(request):
    return render(request,'ecommerce_app/home.html')

def admin_login(request):
    return render(request,'ecommerce_app/admin_login.html')
    
def customer_signup(request):
    msg=''
    if request.method=='POST':
        customer_name=request.POST['name'].lower()
        customer_mobile=request.POST['mobileno']
        customer_mail=request.POST['email']
        customer_password=request.POST['password']
        customer_exist = Customer.objects.filter(customermail= customer_mail).exists()
        if not customer_exist:
          new_customer=Customer(
            customername=customer_name,
            customermobile=customer_mobile,
            customermail=customer_mail,
            customerpassword=customer_password

        )
        new_customer.save()
        msg='Account Registerd Succesfully'
    else:
        msg='Account already Exists'
        
    return render(request,'ecommerce_app/customer_signup.html',{'message': msg})

def customer_login(request):
    msg=''
    if request.method=='POST':
        email=request.POST['email']
        password=request.POST['password']

        try:
            customer = Customer.objects.get(customermail = email , customerpassword = password)
            request.session['customer'] = customer.id
            return redirect('customer_app:home')
        except:
            msg='incorrect'

    return render(request,'ecommerce_app/customer_login.html',{'message':msg})

def seller_login(request):
    msg = ''
    if request.method == 'POST':
        user_name = request.POST['username']
        password = request.POST['password']

        try:
            seller = Seller1.objects.get(username = user_name, password = password)
            request.session['seller'] = seller.id
            return redirect('seller_app:home')
        except:
            msg = 'Incorrect Username or Password'


    return render(request,'ecommerce_app/seller_login.html',{'message': msg})

def seller_signup(request):
    msg = ''
    if request.method =='POST':
        seller_name=request.POST['name'].lower()
        mobile_no=request.POST['mobileno']
        s_email=request.POST['email']
        co_name=request.POST['company']
        s_username=random.randint(1111,9999)
        s_password='sel-'+str(s_username)
        seller_ac_holder_name = request.POST['ac_holder_name']
        seller_ifsc = request.POST['ifsc']
        seller_branch = request.POST['branch']
        seller_ac_no = request.POST['ac_no']
        seller_gender = request.POST['gender']
        seller_image = request.FILES['image']

        seller_exist = Seller1.objects.filter(email = s_email).exists()

        if not seller_exist:

            new_seller = Seller1(
                sellername = seller_name,
                mobileno = mobile_no,
                email = s_email,
                companyname = co_name,
                username = s_username,
                password = s_password,
                ac_holder_name = seller_ac_holder_name,
                ifsc = seller_ifsc,
                branch = seller_branch,
                ac_no = seller_ac_no,
                gender = seller_gender,
                image = seller_image,
            )
            new_seller.save()
            msg = 'Account Created Succesfully'

        else:
            msg = 'Email Exist'

        # msg='Hi Your User Name '+str(s_username)+'and your password is'+s_password
        # send_mail(
        #     'username and password',
        #     msg,
        #      settings.EMAIL_HOST_USER,
        #     [s_email]
            
        # )


    return render(request,'ecommerce_app/seller_signup.html',{'message': msg})

ecommerce_app/templates/ecommerce_app/admin_login.html
{% extends "ecommerce_app/master.html" %}
{% load static %}
{% block header %}


{% endblock %}



{% block content %}

<div class="container-fluid admin-login">



  <table>
    <form method="post" action="#">
      <tr>
        <td>
          <h1>Admin</h1>
        </td>
        <td>
          <h1>Login</h1>
        </td>
      </tr>
      <tr>
        <td>Username:</td>
        <td><input type="text" name="username" required></td>
      </tr>
      <tr>
        <td>Password:</td>
        <td><input type="password" name="password" required></td>
      </tr>
      <tr>
        <td></td>
        <td><input type="submit" value="Login"></td>
      </tr>
    </form>
  </table>


</div>

{% endblock %}

ecommerce_app/templates/ecommerce_app/customer_login.html
{% extends "ecommerce_app/master.html" %}
{% load static %}
{% block header %}
 

{% endblock %}



{% block content %}

    <div class="container-fluid admin-login">
        
           
      
      <table>
        <form method="POST" action="">
          {% csrf_token %}
          <tr>
            <td><h1>Customer</h1></td>
            <td><h1>Login</h1></td>
          </tr>
          <tr>
            <td>Email:</td>
            <td><input type="text" name="email" required></td>
          </tr>
          <tr>
            <td>Password:</td>
            <td><input type="password" name="password" required></td>
          </tr>
          <tr>
            <td></td>
            <td> <button type="submit" class="btn btn-success">Login</button> </td>
          </tr>
          <tr>
            <td></td>
            <td>Don't have an account <a href="{% url 'ecommerce_app:customer_signup'%}">Sign up</a></td>
          </tr>
        </form>
      </table>
           
        
    </div>
    
{% endblock %}

ecommerce_app/templates/ecommerce_app/customer_signup.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet"
		href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
	<link rel="stylesheet"
		href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
	<style>
		nav a {
			text-decoration: none;
			color: black;
		}

		.form {
			display: flex;
			flex-direction: column;
			align-items: center;
			margin-top: 50px;
		}

		input[type=text],
		input[type=email],
		input[type=password] {
			margin: 10px;
			padding: 10px;
			width: 300px;
			border-radius: 5px;
			border: 1px solid #ccc;
		}

		input[type=submit] {
			background-color: #4CAF50;
			color: white;
			border: none;
			padding: 10px 20px;
			text-align: center;
			text-decoration: none;
			/* display: inline-block; */
			font-size: 16px;
			margin: 10px;
			border-radius: 5px;
			cursor: pointer;
			float: right;

		}

		label {
			margin: 10px;
		}

		.signup {
			text-align: center;
		}
	</style>
</head>

<body>
	<header>
		<nav class="navbar bg-body-tertiary nav">
			<div class="container-fluid">
				<a class="navbar-brand" href="#">
					<i class="lab la-amazon"></i>
					Amazon
				</a>
				<i class="las la-home"><a href="{% url 'ecommerce_app:home'%}"> Home</a></i>
			</div>

		</nav>
	</header>

	<div class="container-fluid form">
		<div class="signup">
			<h3>CUSTOMER SIGNUP</h3><br>
			<p></p>
		</div>

		<table>
			{{ message }}
			<form method="POST">
				{% csrf_token %}
				<tr>
					<td><label for="name">Name:</label></td>
					<td><input type="text" id="name" name="name" placeholder="Enter your name" required>
					</td>
				</tr>
				<tr>
					<td><label for="mobilno">mobil no:</label></td>
					<td><input type="text" id="mobileno" placeholder="Enter your mobile number" name="mobileno"
							required></td>
				</tr>

				<tr>
					<td><label for="email">Email:</label></td>
					<td><input type="email" id="email" name="email" placeholder="Enter your email" required></td>
				</tr>
				<tr>
					<td><label for="password">Password :</label></td>
					<td><input type="password" name="password" id="password" placeholder="Enter a Password"></td>
				</tr>


				<tr>
					<td></td>
					<td><input type="submit" value="Submit"></td>
				</tr>

			</form>
		</table>
	</div>

ecommerce_app/templates/ecommerce_app/home.html
{% extends "ecommerce_app/master.html" %}
{% load static %}
{% block header %}


{% endblock %}




{% block content %}





<div class="container-fluid main">


  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h4 class="card-title">Admin</h4>
      <h6 class="card-subtitle mb-2 text-body-secondary"></h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
        content.</p>
      <a href="{% url 'ecommerce_app:admin_login'%}" class="card-link">Login</a>

    </div>
  </div>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h4 class="card-title">Seller</h4>
      <h6 class="card-subtitle mb-2 text-body-secondary"> </h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
        content.</p>
      <a href="{% url 'ecommerce_app:seller_login'%}" class="card-link">Login</a>
      <a href="{% url 'ecommerce_app:seller_signup'%}" class="card-link">Sign Up</a>
    </div>
  </div>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h4 class="card-title">Customer</h4>
      <h6 class="card-subtitle mb-2 text-body-secondary"> </h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
        content.</p>
      <a href="{% url 'ecommerce_app:customer_login'%}" class="card-link">Login</a>
      <a href="{% url 'ecommerce_app:customer_signup'%}" class="card-link">Sign Up</a>
    </div>
  </div>

</div>

{% endblock %}

ecommerce_app/templates/ecommerce_app/master.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="{% static 'css/master.css' %}">

    <link rel="stylesheet"
        href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
    <link rel="stylesheet"
        href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    {% block header %}

    {% endblock %}
</head>

<body>
    <header>
        <nav class="navbar bg-body-tertiary nav">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    <i class="lab la-amazon"></i>
                    Amazon
                </a>
                <i class="las la-home"><a href="{% url 'ecommerce_app:home'%}"> Home</a></i>
            </div>

        </nav>
    </header>




    <div class="container-fluid">
        {% block content %}

        {% endblock %}
    </div>


</body>

</html>

ecommerce_app/templates/ecommerce_app/seller_login.html
{% extends "ecommerce_app/master.html" %}
{% load static %}
{% block header %}


{% endblock %}



{% block content %}

<div class="container-fluid admin-login">



  <table>
    {{ message }}
    <form method="POST" action="">
      {% csrf_token %}
      <tr>
        <td>
          <h1>Seller</h1>
        </td>
        <td>
          <h1>Login</h1>
        </td>
      </tr>
      <tr>
        <td>Username:</td>
        <td><input type="text" name="username" required></td>
      </tr>
      <tr>
        <td>Password:</td>
        <td><input type="password" name="password" required></td>
      </tr>
      <tr>
        <td></td>
        <td> <button type="submit" class="btn btn-success">Login</button> </td>
      </tr>
      <tr>
        <td></td>
        <td>Don't have an account <a href="{% url 'ecommerce_app:seller_signup'%}">Sign up</a></td>
      </tr>
    </form>
  </table>


</div>

{% endblock %}

ecommerce_app/templates/ecommerce_app/seller_signup.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet"
		href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
	<link rel="stylesheet"
		href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
	<style>
		.nav a {
			text-decoration: none;
			color: black;

		}

		.form {
			display: flex;
			flex-direction: column;
			align-items: center;
			margin-top: 50px;
		}

		input[type=text],
		input[type=email],
		input[type=password] {
			margin: 10px;
			padding: 10px;
			width: 300px;
			border-radius: 5px;
			border: 1px solid #ccc;
		}

		input[type=submit] {
			background-color: #4CAF50;
			color: white;
			border: none;
			padding: 10px 20px;
			text-align: center;
			text-decoration: none;
			/* display: inline-block; */
			font-size: 16px;
			margin: 10px;
			border-radius: 5px;
			cursor: pointer;
			float: right;
		}

		label {
			margin: 10px;

		}

		.signup {
			text-align: center;
		}
	</style>
</head>

<body>
	<header>
		<nav class="navbar bg-body-tertiary nav">
			<div class="container-fluid">
				<a class="navbar-brand" href="#">
					<i class="lab la-amazon"></i>
					Amazon
				</a>
				<i class="las la-home"><a href="{% url 'ecommerce_app:home'%}"> Home</a></i>
			</div>

		</nav>
	</header>

	<div class="container-fluid form">
		<div class="signup">
			<h3>SELL ON AMAZON</h3><BR>
			<P>Sign Up</P></BR>
		</div>
		<table>
			{{ message }}
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<tr>
					<td><label for="name">Name:</label></td>
					<td><input type="text" id="name" name="name" placeholder="Enter your name" required>
					</td>
				</tr>
				<tr>
					<td><label for="mobilno">mobil no:</label></td>
					<td><input type="text" id="mobileno" name="mobileno" placeholder="Enter your mobile number"
							required></td>
				</tr>
				<tr>
					<td><label for="">Gender</label></td>
					<td> <select name="gender" id="">
							<option value="Male">Male</option>
							<option value="Female">Female</option>
						</select></td>
				</tr>

				<tr>
					<td><label for="email">Email:</label></td>
					<td><input type="email" id="email" name="email" placeholder="Enter your email" required></td>
				</tr>
				<tr>
					<td><label for="company-name">Company Name :</label></td>
					<td><input type="text" id="co_name" name="company" placeholder="Enter Your Company Name"></td>
				</tr>
				<tr>
					<td><label for="">AC Holder Name</label></td>
					<td><input type="text" name="ac_holder_name"></td>

				</tr>
				<tr>
					<td><label for="">AC NO</label></td>
					<td><input type="text" name="ac_no"></td>
				</tr>
				<tr>
					<td><label for="">ifsc</label></td>
					<td><input type="text" name="ifsc"></td>
				</tr>
				<tr>
					<td><label for="">Branch</label></td>
					<td><input type="text" name="branch"></td>
				</tr>
				<tr>
					<td><label for="">Image</label></td>
					<td><input type="file" name="image"></td>
				</tr>

				<tr>

					<td></td>
					<td><input type="submit" value="Submit"></td>
				</tr>

			</form>
		</table>
	</div>

</body>

</html>